version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
  #gateway: https://openfaas-ingress-janaka-steph.cloud.okteto.net
functions:
  openfaas-nginx-react:
    lang: dockerfile
    handler: ./function
    image: janakasteph/openfaas-nginx-react
    environment:
      write_debug: true